apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crashloop-app
  template:
    metadata:
      labels:
        app: crashloop-app
    spec:
      containers:
      - name: bad-container
        image: alpine:latest
        command: ["./nonexistent-script.sh"]
        ports:
        - containerPort: 80
