-- 20250904_create_cluster_state_pairs.sql
-- Purpose: Create a table to store paired "sick" vs "healthy" Kubernetes states.

BEGIN;

CREATE TABLE IF NOT EXISTS public.cluster_state_pairs (
    cluster_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sick_deployment_yaml                  TEXT,
    healthy_deployment_yaml               TEXT,

    sick_service_yaml                     TEXT,
    healthy_service_yaml                  TEXT,

    sick_kubectl_cluster_info             TEXT,
    healthy_kubectl_cluster_info          TEXT,

    sick_kubectl_get_nodes                TEXT,
    healthy_kubectl_get_nodes             TEXT,

    sick_kubectl_get_pods                 TEXT,
    healthy_kubectl_get_pods              TEXT,

    sick_kubectl_top_nodes                TEXT,
    healthy_kubectl_top_nodes             TEXT,

    sick_kubectl_top_pods                 TEXT,
    healthy_kubectl_top_pods              TEXT,

    sick_kubectl_get_componentstatuses    TEXT,
    healthy_kubectl_get_componentstatuses TEXT,

    sick_kubectl_get_events               TEXT,
    healthy_kubectl_get_events            TEXT
);

COMMIT;

